title: ðŸ“š Luciano's Library
description: Tech skills, interview tips, life hacks, and documentation guides from a Chilean CloudOps Engineer. Learn Confluence, Airtable, OKRs, and more.
url: "https://lucianoadonis.github.io/"
plugins:
- jekyll-seo-tag
kramdown:
  toc_levels: 2..3

vars:
  example_email: test@gmail.com
  example_email_plus_a: test+a@gmail.com
  example_email_plus_b: test+b@gmail.com

show_links: true
links:
  github: https://lucianoadonis.github.io/
  youtube: https://www.youtube.com/@energon-hq/
